baseURL: "https://www.cybersmith.co.uk/"
title: "Cybersmith"
languageCode: "en-GB"
disableKinds: ["taxonomy", "RSS"]
enableRobotsTXT: true
disableHugoGeneratorInject: true
sitemap:
    changefreq: monthly
